### ISSUE TITLE
Auth is not inherited

### ISSUE THREAD

**Issue by Altai-man** [finanalyst/raku-pod-render#1]
Currently, the module is unusable, because it is, apparently, assumed `:auth<>` will be propagated from distribution level to classes.

E.g. https://github.com/finanalyst/raku-pod-render/blob/master/lib/Pod/To/HTML2.pm6#L1 <- here it assumes `Pod::To::HTML` class will have auth set (with a typo, by the way), but https://github.com/finanalyst/raku-pod-render/blob/master/lib/Pod/To/HTML.pm6#L32 definition lacks actual `:auth<github:finanalyst>` specification, so it starts to panic and cannot be used by other classes.

`use lib 'lib'` at https://github.com/finanalyst/raku-pod-render/blob/master/bin/read-y-me.raku#L2 is not needed anymore, more so it is harmful and breaks the module installation.

Rakudo is 2020.06.

**Comment by finanalyst** [comment]
@Altai-man Thank you very much for this help. I saw your comment regarding pod. Looked at the code to do a PR.
