### ISSUE TITLE
Cro::WebApp::Template::Repository::Build doesn't exists

### ISSUE THREAD

**Issue by vrurg** [finanalyst/raku-pod-render#10]
Upgrading of `Raku::Pod::Render` fails with:

```
Failed to resolve some missing dependencies (use e.g. --exclude="Cro::WebApp::Template::Repository::Build" to skip)
```

The error message is correct: there is no such module in the ecosystem.

**Comment by finanalyst** [comment]
Issue is resolved. The META6.json errors in CWT-Repository-Hash have been eliminated, and the testing environment for this module has been amended so that tests pass.
