### ISSUE TITLE
Re-use of link text in generated pages

### ISSUE THREAD

**Issue by cfa** [finanalyst/raku-pod-render#16]
Links to the same target from a given source document seem to re-use the first link's text.

For example:

- https://docs-dev.raku.org/language/subscripts#Zen_slices
  - This currently renders as "Zen slicing does not [reification](https://docs-dev.raku.org/language/glossary.html#index-entry-Reify) or [cache](https://docs-dev.raku.org/routine/cache.html)…" 
  - The underlying POD is `Zen slicing does not L<reify|/language/glossary#index-entry-Reify> or L<cache|/routine/cache>` (see [here](https://github.com/Raku/doc/blob/main/doc/Language/subscripts.rakudoc#L340-L341)).
    - Note that the link text reads "reify", not "reification"—but the latter is used in the HTML.
  - Earlier text on that [page](https://github.com/Raku/doc/blob/main/doc/Language/subscripts.rakudoc#L250):
    - `L<reification|/language/glossary#index-entry-Reify>`.
- https://docs-dev.raku.org/type/DateTime#method_local
  - "Returns a DateTime object for the same time, but in the local time zone ([$*TZ variable](https://docs.raku.org/language/variables.html#index-entry-%24*TZ))."
  - Underlying POD: `Returns a DateTime object for the same time, but in the local time zone (L«C<$*TZ>|/language/variables#index-entry-%24*TZ»).` (see [here](https://github.com/Raku/doc/blob/main/doc/Type/DateTime.rakudoc#L392-L393))
    - Note that the link text reads "$*TZ", not "$*TZ variable".
  - Earlier text on that [page](https://github.com/Raku/doc/blob/main/doc/Type/DateTime.rakudoc#L114): 
    - `and defaults to the value of L«C<$*TZ> variable|/language/variables#index-entry-%24*TZ».`

**Comment by cfa** [comment]
Since those [doc](https://github.com/Raku/doc) link targets may be updated soon, here's a reproduction that doesn't depend on the state of that repo.

Create file `demo.pod6` containing

```raku
=begin pod

L<one|/a>, L<two|/a> and L<three|/b>.

=end pod
```

and generate HTML:

```
$ Rakudoc-to-html demo.pod6 
demo.html has been generated in the local directory.
```

This currently creates a document with the following links:

> [one](https://github.com/a.html), [one](https://github.com/a.html) and [three](https://github.com/b.html).

Note that the second incorrectly reads "one" (instead of "two").

Here's the relevant HTML:

```
$ grep one demo.html 
<img id="Camelia_bug" src="/asset_files/images/Camelia.svg"><h1 class="title">NO_TITLE</h1></header><div class="pod-content"><div id=""></div><div class="pod-body no-toc"><section name="___top"><p><a href="/a.html">one</a>, <a href="/a.html">one</a> and <a href="/b.html">three</a>.</p></section>		</div>
```

namely `<a href="/a.html">one</a>, <a href="/a.html">one</a> and <a href="/b.html">three</a>.`

**Comment by cfa** [comment]
(@coke FYI)

**Comment by finanalyst** [comment]
@cfa I'm under a bit of pressure at the moment with other commitments. I'll
respond here as soon as I find time.

**Comment by cfa** [comment]
No worries.

**Comment by finanalyst** [comment]
@cfa @coke The problem is that `raku-pod-render` caches each link, together with the label. So when the link appears again, the cached label (first one) is used. Thinking about how to retain the cache but ensure that the proper label is used. 
@cfa Thanks for golfing down the problem

**Comment by finanalyst** [comment]
So the question now is whether to cache each link-label pair. The link registry is used to verify whether expected links exist, which does not need unique label information. If the link does not exist, then all labels to that link (url) will not exist. But at least one label is needed to help in the debug process. So the first label will be cached with the link, but the label will be returned as received.
