### ISSUE TITLE
Can not install with zef

### ISSUE THREAD

**Issue by lizmat** [finanalyst/raku-pod-render#3]
$ zef install Raku::Pod::Render
    ===> Searching for: Raku::Pod::Render
    ===> Testing: Raku::Pod::Render:ver<2.3>:auth<github:finanalyst>
    ===> Testing [OK] for Raku::Pod::Render:ver<2.3>:auth<github:finanalyst>
    ===> Installing: Raku::Pod::Render:ver<2.3>:auth<github:finanalyst>
    ===> Install [FAIL] for Raku::Pod::Render:ver<2.3>:auth<github:finanalyst>: ===SORRY!=== Error while compiling /Users/liz/Github/json_fast/site#sources/6EB9C0F475E8BB1A48B002DFE8B31814F001A366 (Pod::To::HTML2)
    Could not find Pod::To::HTML:auth<github:finanalyt> in:
        inst#/Users/liz/Github/rakudo.moar/install/share/perl6/site
        inst#/Users/liz/Github/rakudo.moar/install/share/perl6/vendor
        inst#/Users/liz/Github/rakudo.moar/install/share/perl6/core
        ap#
        nqp#
        perl5#
    at /Users/liz/Github/json_fast/site#sources/6EB9C0F475E8BB1A48B002DFE8B31814F001A366 (Pod::To::HTML2):1

    ===SORRY!=== Error while compiling /Users/liz/Github/json_fast/site#sources/6EB9C0F475E8BB1A48B002DFE8B31814F001A366 (Pod::To::HTML2)
    Could not find Pod::To::HTML:auth<github:finanalyt> in:
        inst#/Users/liz/Github/rakudo.moar/install/share/perl6/site
        inst#/Users/liz/Github/rakudo.moar/install/share/perl6/vendor
        inst#/Users/liz/Github/rakudo.moar/install/share/perl6/core
        ap#
        nqp#
        perl5#
    at /Users/liz/Github/json_fast/site#sources/6EB9C0F475E8BB1A48B002DFE8B31814F001A366 (Pod::To::HTML2):1

**Comment by antoniogamiz** [comment]
I'm getting another error too:

~~~
===> Install [FAIL] for Pod::Render:ver<0.8.0>: ===SORRY!=== Error while compiling /home/antonio/raku/Documentable/raku-testing/site#sources/52EABBE240A4E78D4EFE7FB3EA000854226A349F (Pod::Render)
P6M Merging GLOBAL symbols failed: duplicate definition of symbol HTML
at /home/antonio/raku/Documentable/raku-testing/site#sources/52EABBE240A4E78D4EFE7FB3EA000854226A349F (Pod::Render):3

===SORRY!=== Error while compiling /home/antonio/raku/Documentable/raku-testing/site#sources/52EABBE240A4E78D4EFE7FB3EA000854226A349F (Pod::Render)
P6M Merging GLOBAL symbols failed: duplicate definition of symbol HTML
at /home/antonio/raku/Documentable/raku-testing/site#sources/52EABBE240A4E78D4EFE7FB3EA000854226A349F (Pod::Render):3
~~~

I suppose I cannot have the old version and the new one.

**Comment by finanalyst** [comment]
First issue has been rectified.
Second issue relates to old version
