### ISSUE TITLE
Arbitrary attributes of Template::Mustache

### ISSUE THREAD

**Issue by antoniogamiz** [finanalyst/raku-pod-render#6]
In the legacy `Pod::To::HTML`, you can use arbitrary arguments with `render`. I mean, for instance, if I declare a variable `{{name}}` inside my template,  I can later pass a `name => "foo"` to the `render` method. Is this possible? I have not found a way to do it.

**Comment by finanalyst** [comment]
- I have moved the default template system to my own RakuClosure. These are MUCH faster than Mustache and far far more flexible. 
- I need a bit more help understanding the use case you mentioned.

**Comment by finanalyst** [comment]
No response about use case
