### ISSUE TITLE
GTK::Simple dependency is a problem

### ISSUE THREAD

**Issue by JJ** [finanalyst/raku-pod-render#8]
Because it's only used in the binary file, not in the library itself. Clients of the library are going to download a distribution they don't need, and it's going to cause problems [down the line](https://travis-ci.com/github/Raku/ecosystem/builds/182841116)

**Comment by finanalyst** [comment]
The problem is with GTK::Simple.  I'm trying to solve it, but the problem is with Windows. I have asked for help on this. I have changed the name of the module Pod::To::HTML so it should not be a great problem.
